import type { Dictionary, Locale, Translate } from "@clove/core";

/** Texte der Shell. Die Spiele bringen ihre eigenen (aus den Originalen). */
const DE = {
  settings: "Einstellungen",
  back: "Zurück",
  comingSoon: "folgt",
  debugAssets: "Assets ansehen (Debug)",
  debugLevel: "Level-Skripte ansehen (Debug)",
  doveSub: "1999–2003 · Horizontal-Shooter, 12 Level",
  dovezSub: "2004–2019 · The Second Wave, 27 Level",
  offlineReady: "offline spielbar",
  offlinePartial: "{percent} % offline gespeichert",
  offlineNone: "nicht offline gespeichert",
  loadFailed: "{title} konnte nicht gestartet werden.",
  notFound: "Unbekannte Seite „{path}“.",
  language: "Sprache",
  languageAuto: "Automatisch (Browser)",
  volume: "Lautstärke",
  volumeMaster: "Gesamt",
  volumeMusic: "Musik",
  volumeSfx: "Effekte",
  gamepad: "Gamepad",
  gamepadUse: "Gamepad verwenden",
  gamepadNone: "Kein Gamepad erkannt — eine Taste am Pad drücken.",
  gamepadConnected: "Erkannt: {name}",
  gamepadHelp:
    "Steuerkreuz/Stick bewegen, A bestätigt, B zurück, Start pausiert. Die Belegung je Spiel zeigen der Launcher und die Pause unter „Steuerung“.",
  motion: "Bewegung",
  motionAuto: "wie das System",
  motionReduce: "reduzieren",
  motionFull: "volle Effekte",
  motionHelp:
    "Reduziert Bildschirmwackeln und schwächt Vollbildblitze ab; das Spielgeschehen bleibt gleich.",
  display: "Darstellung",
  scale: "Skalierung",
  scaleInteger: "ganzzahlig (scharf, wie das Original)",
  scaleFit: "Fenster füllen (scharf)",
  scaleSmooth: "Fenster füllen (weich)",
  scaleHelp:
    "„Fenster füllen“ (Vorgabe) nutzt den ganzen Platz, „ganzzahlig“ zeigt jedes Originalpixel als exaktes Quadrat ohne Filter. Vollbild: Alt+Enter oder ⛶ oben rechts.",
  resolution: "Auflösung",
  resolutionOriginal: "Original",
  resolutionXbr: "Kanten geglättet (xBR)",
  resolutionHd: "HD (Bildschirmauflösung)",
  resolutionHelp:
    "„Kanten geglättet“ rundet die Treppen an schrägen Kanten der Pixelgrafik ab. „HD“ zeichnet in der Auflösung des Bildschirms: Drehungen, Überblendungen, Linien und Schrift werden schärfer, die Pixelgrafik bleibt. Beides braucht mehr Grafikleistung.",
  scanlines: "Rasterlinien (Röhrenmonitor)",
  fullscreen: "Vollbild",
  fullscreenExit: "Vollbild beenden",
  controls: "Steuerung",
  colAction: "Aktion",
  colKeyboard: "Tastatur",
  colMouse: "Maus",
  keySpace: "Leertaste",
  mouseLeft: "linke Taste",
  mouseRight: "rechte Taste",
  mouseMiddle: "mittlere Taste",
  mouseWheel: "Mausrad",
  mouseWheelUp: "Rad hoch",
  mouseWheelDown: "Rad runter",
  pointerUse: "Maus und Touch steuern das Schiff",
  pointerHelp:
    "Maus: das Schiff folgt dem Zeiger, links Feuer, rechts Beam, Rad Tempo (DOVE) bzw. Waffenwechsel (DoveZ). Touch: Finger ziehen lenkt und feuert, zweiter Finger lädt den Beam. Pfeiltasten übernehmen jederzeit.",
  touchBack: "Zurück / Pause",
  hud: "Anzeige (HUD)",
  hudModern: "modern (neben dem Spielfeld, mit Boss-Balken)",
  hudOriginal: "Original (im Spielbild)",
  hudHelp:
    "Das moderne HUD zeigt Punkte, Leben, Energie, Beam und Waffen gut lesbar neben dem Spielfeld und die Lebenspunkte der Bosse; das Spielfeld wird dafür größer.",
  hudScore: "Punkte",
  hudPlayer: "Spieler",
  hudLives: "Leben",
  hudEnergy: "Energie",
  hudBeam: "Beam",
  hudShield: "Schild",
  hudSpeed: "Tempo",
  hudPower: "Stärke",
  hudBoss: "Boss",
  hudCombo: "Kombo {hits} · +{bonus}",
  hudBossAppears: "Ein Boss greift an.",
  hudBossDefeated: "Boss besiegt.",
  hudLifeLost: "Ein Leben verloren.",
  keysTitle: "Tastenbelegung {title}",
  keysHelp:
    "Vorlage wählen oder je Aktion bis zu drei Tasten belegen: Enter (oder Klick) und dann die Taste drücken; Rücktaste entfernt die letzte, Esc bricht ab. Gilt mit „Übernehmen“.",
  keysPreset: "Vorlage",
  keysApply: "Übernehmen",
  keysMissing: "Ohne Taste: {actions}",
  keysDuplicate: "Doppelt belegt: {keys}",
  keysGroupMove: "Bewegen",
  keysGroupWeapon: "Waffen",
  keysGroupSystem: "Sonstiges",
  keysPlayer: "Spieler {n} · {group}",
  volumeVoice: "Sprache",
  on: "an",
  off: "aus",
  loadingBar: "Ladefortschritt",
  gameCanvas: "{title}: Spielfläche. Bedienung mit Tastatur oder Gamepad, Esc pausiert.",
  saves: "Spielstände",
  savesHelp:
    "Optionen, Freischaltungen und Highscores liegen im Browser und können dort jederzeit gelöscht werden. Als Datei sichern:",
  export: "Exportieren",
  import: "Importieren …",
  imported: "Importiert: {games}.",
  importFailed: "Import fehlgeschlagen: {error}",
  offline: "Offline-Daten",
  offlineHelp:
    "Lädt alle Spieldaten einmal vollständig in den Browser-Cache; danach startet das Spiel ohne Netz.",
  install: "Spieldaten installieren ({size} MB)",
  remove: "Entfernen",
  persisted: "Der Browser behält die Daten dauerhaft.",
  notPersisted: "Der Browser darf die Daten bei Platzmangel löschen.",
  storageUsage: "Belegt: {used} MB von {quota} MB",
  noServiceWorker:
    "Offline-Betrieb nicht verfügbar (Entwicklungsserver oder Browser ohne Service Worker).",
};

export type TextKey = keyof typeof DE;
export type ShellText = Translate<TextKey>;

export const TEXTS: Readonly<Record<Locale, Dictionary<TextKey>>> = {
  de: DE,
  en: {
    settings: "Settings",
    back: "Back",
    comingSoon: "coming later",
    debugAssets: "View assets (debug)",
    debugLevel: "View level scripts (debug)",
    doveSub: "1999–2003 · horizontal shooter, 12 levels",
    dovezSub: "2004–2019 · The Second Wave, 27 levels",
    offlineReady: "playable offline",
    offlinePartial: "{percent} % stored offline",
    offlineNone: "not stored offline",
    loadFailed: "{title} could not be started.",
    notFound: "Unknown page “{path}”.",
    language: "Language",
    languageAuto: "Automatic (browser)",
    volume: "Volume",
    volumeMaster: "Master",
    volumeMusic: "Music",
    volumeSfx: "Effects",
    gamepad: "Gamepad",
    gamepadUse: "Use gamepad",
    gamepadNone: "No gamepad detected — press a button on the pad.",
    gamepadConnected: "Detected: {name}",
    gamepadHelp:
      "D-pad/stick move, A confirms, B goes back, Start pauses. The launcher and the pause menu show each game's layout under “Controls”.",
    motion: "Motion",
    motionAuto: "as system",
    motionReduce: "reduce",
    motionFull: "full effects",
    motionHelp: "Reduces screen shake and softens full-screen flashes; gameplay stays the same.",
    display: "Display",
    scale: "Scaling",
    scaleInteger: "integer (sharp, as the original)",
    scaleFit: "fill window (sharp)",
    scaleSmooth: "fill window (smooth)",
    scaleHelp:
      "“Fill window” (default) uses all the space; integer shows every original pixel as an exact square without filtering. Full screen: Alt+Enter or ⛶ at the top right.",
    resolution: "Resolution",
    resolutionOriginal: "original",
    resolutionXbr: "smoothed edges (xBR)",
    resolutionHd: "HD (screen resolution)",
    resolutionHelp:
      "“Smoothed edges” rounds off the stair steps on diagonal edges of the pixel art. “HD” renders at the screen's resolution: rotations, blending, lines and text get sharper; the pixel art stays. Both need more graphics power.",
    scanlines: "Scanlines (CRT look)",
    fullscreen: "Full screen",
    fullscreenExit: "Exit full screen",
    controls: "Controls",
    colAction: "Action",
    colKeyboard: "Keyboard",
    colMouse: "Mouse",
    keySpace: "Space",
    mouseLeft: "left button",
    mouseRight: "right button",
    mouseMiddle: "middle button",
    mouseWheel: "wheel",
    mouseWheelUp: "wheel up",
    mouseWheelDown: "wheel down",
    pointerUse: "Mouse and touch steer the ship",
    pointerHelp:
      "Mouse: the ship follows the pointer, left fires, right charges the beam, wheel changes speed (DOVE) or weapon (DoveZ). Touch: drag to steer and fire, a second finger charges the beam. Arrow keys take over at any time.",
    touchBack: "Back / pause",
    hud: "HUD",
    hudModern: "modern (beside the play field, with boss bar)",
    hudOriginal: "original (inside the picture)",
    hudHelp:
      "The modern HUD shows score, lives, energy, beam and weapons legibly beside the play field, plus boss health; the play field gets bigger.",
    hudScore: "Score",
    hudPlayer: "Player",
    hudLives: "Lives",
    hudEnergy: "Energy",
    hudBeam: "Beam",
    hudShield: "Shield",
    hudSpeed: "Speed",
    hudPower: "Power",
    hudBoss: "Boss",
    hudCombo: "Combo {hits} · +{bonus}",
    hudBossAppears: "A boss attacks.",
    hudBossDefeated: "Boss defeated.",
    hudLifeLost: "Life lost.",
    keysTitle: "{title} key bindings",
    keysHelp:
      "Pick a preset or bind up to three keys per action: Enter (or click), then press the key; Backspace removes the last one, Esc cancels. Takes effect with “Apply”.",
    keysPreset: "Preset",
    keysApply: "Apply",
    keysMissing: "No key: {actions}",
    keysDuplicate: "Bound twice: {keys}",
    keysGroupMove: "Movement",
    keysGroupWeapon: "Weapons",
    keysGroupSystem: "Other",
    keysPlayer: "Player {n} · {group}",
    volumeVoice: "Voices",
    on: "on",
    off: "off",
    loadingBar: "Loading progress",
    gameCanvas: "{title}: play area. Controls: keyboard or gamepad, Esc pauses.",
    saves: "Saved games",
    savesHelp:
      "Options, unlocked levels and high scores live in the browser and may be deleted at any time. Keep a copy as a file:",
    export: "Export",
    import: "Import …",
    imported: "Imported: {games}.",
    importFailed: "Import failed: {error}",
    offline: "Offline data",
    offlineHelp:
      "Downloads all game data into the browser cache once; afterwards the game starts without a network.",
    install: "Install game data ({size} MB)",
    remove: "Remove",
    persisted: "The browser keeps the data permanently.",
    notPersisted: "The browser may delete the data when space runs low.",
    storageUsage: "Used: {used} MB of {quota} MB",
    noServiceWorker: "Offline mode unavailable (dev server or browser without service workers).",
  },
  ru: {
    settings: "Настройки",
    back: "Назад",
    comingSoon: "скоро",
    debugAssets: "Просмотр ассетов (отладка)",
    debugLevel: "Просмотр скриптов уровней (отладка)",
    doveSub: "1999–2003 · горизонтальный шутер, 12 уровней",
    dovezSub: "2004–2019 · The Second Wave",
    offlineReady: "доступно офлайн",
    offlinePartial: "{percent} % сохранено офлайн",
    offlineNone: "не сохранено офлайн",
    loadFailed: "Не удалось запустить {title}.",
    notFound: "Неизвестная страница «{path}».",
    language: "Язык",
    languageAuto: "Автоматически (браузер)",
    volume: "Громкость",
    volumeMaster: "Общая",
    volumeMusic: "Музыка",
    volumeSfx: "Эффекты",
    gamepad: "Геймпад",
    gamepadUse: "Использовать геймпад",
    gamepadNone: "Геймпад не обнаружен — нажмите кнопку на геймпаде.",
    gamepadConnected: "Обнаружен: {name}",
    gamepadHelp:
      "Крестовина/стик — движение, A — подтвердить, B — назад, Start — пауза. Раскладку каждой игры показывают лаунчер и пауза в разделе «Управление».",
    motion: "Движение",
    motionAuto: "как в системе",
    motionReduce: "уменьшить",
    motionFull: "полные эффекты",
    motionHelp:
      "Убирает тряску экрана и ослабляет вспышки на весь экран; игровой процесс не меняется.",
    display: "Изображение",
    scale: "Масштаб",
    scaleInteger: "целочисленный (чёткий, как в оригинале)",
    scaleFit: "по размеру окна (чёткий)",
    scaleSmooth: "по размеру окна (сглаженный)",
    scaleHelp:
      "«По размеру окна» (по умолчанию) использует всё место, целочисленный масштаб показывает каждый пиксель оригинала точным квадратом без фильтрации. Полный экран: Alt+Enter или ⛶ справа вверху.",
    resolution: "Разрешение",
    resolutionOriginal: "оригинальное",
    resolutionXbr: "сглаженные края (xBR)",
    resolutionHd: "HD (разрешение экрана)",
    resolutionHelp:
      "«Сглаженные края» скругляют ступеньки на наклонных краях пиксельной графики. «HD» рисует в разрешении экрана: повороты, наложения, линии и текст становятся чётче, пиксельная графика остаётся. Оба режима требуют больше ресурсов видеокарты.",
    scanlines: "Строки развёртки (как на ЭЛТ)",
    fullscreen: "Полный экран",
    fullscreenExit: "Выйти из полноэкранного режима",
    controls: "Управление",
    colAction: "Действие",
    colKeyboard: "Клавиатура",
    colMouse: "Мышь",
    keySpace: "Пробел",
    mouseLeft: "левая кнопка",
    mouseRight: "правая кнопка",
    mouseMiddle: "средняя кнопка",
    mouseWheel: "колесо",
    mouseWheelUp: "колесо вверх",
    mouseWheelDown: "колесо вниз",
    pointerUse: "Мышь и касание управляют кораблём",
    pointerHelp:
      "Мышь: корабль следует за указателем, левая кнопка — огонь, правая — луч, колесо — скорость (DOVE) или смена оружия (DoveZ). Касание: ведите пальцем для движения и огня, второй палец заряжает луч. Стрелки перехватывают управление в любой момент.",
    touchBack: "Назад / пауза",
    hud: "Интерфейс (HUD)",
    hudModern: "современный (рядом с полем, с полосой босса)",
    hudOriginal: "оригинальный (в кадре)",
    hudHelp:
      "Современный HUD показывает очки, жизни, энергию, луч и оружие рядом с полем, а также здоровье боссов; игровое поле становится больше.",
    hudScore: "Очки",
    hudPlayer: "Игрок",
    hudLives: "Жизни",
    hudEnergy: "Энергия",
    hudBeam: "Луч",
    hudShield: "Щит",
    hudSpeed: "Скорость",
    hudPower: "Мощь",
    hudBoss: "Босс",
    hudCombo: "Комбо {hits} · +{bonus}",
    hudBossAppears: "Атакует босс.",
    hudBossDefeated: "Босс побеждён.",
    hudLifeLost: "Жизнь потеряна.",
    keysTitle: "Клавиши {title}",
    keysHelp:
      "Выберите шаблон или назначьте до трёх клавиш на действие: Enter (или щелчок), затем клавиша; Backspace удаляет последнюю, Esc отменяет. Действует после «Применить».",
    keysPreset: "Шаблон",
    keysApply: "Применить",
    keysMissing: "Без клавиши: {actions}",
    keysDuplicate: "Назначено дважды: {keys}",
    keysGroupMove: "Движение",
    keysGroupWeapon: "Оружие",
    keysGroupSystem: "Прочее",
    keysPlayer: "Игрок {n} · {group}",
    volumeVoice: "Речь",
    on: "вкл.",
    off: "выкл.",
    loadingBar: "Ход загрузки",
    gameCanvas: "{title}: игровое поле. Управление: клавиатура или геймпад, Esc — пауза.",
    saves: "Сохранения",
    savesHelp:
      "Настройки, открытые уровни и рекорды хранятся в браузере и могут быть удалены в любой момент. Копия в файл:",
    export: "Экспорт",
    import: "Импорт …",
    imported: "Импортировано: {games}.",
    importFailed: "Ошибка импорта: {error}",
    offline: "Офлайн-данные",
    offlineHelp:
      "Один раз загружает все данные игры в кэш браузера; после этого игра запускается без сети.",
    install: "Установить данные игры ({size} МБ)",
    remove: "Удалить",
    persisted: "Браузер хранит данные постоянно.",
    notPersisted: "Браузер может удалить данные при нехватке места.",
    storageUsage: "Занято: {used} МБ из {quota} МБ",
    noServiceWorker: "Офлайн-режим недоступен (сервер разработки или браузер без Service Worker).",
  },
};

/** Megabyte mit einer Nachkommastelle in der Schreibweise der Sprache. */
export function mb(bytes: number, locale: Locale): string {
  return (bytes / 1e6).toLocaleString(locale, {
    minimumFractionDigits: 1,
    maximumFractionDigits: 1,
  });
}
